stages:
  - test
  - build

# Comment to add
test_app:
  stage: test
  image: node:20
  before_script:
    - cd UserApi/app
  services:
    - name: postgres:15
      alias: postgres
  variables:
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD      
  script:
    - echo "DB $POSTGRES_DB"
    - echo "User $POSTGRES_USER"
    - echo "Pass length ${#POSTGRES_PASSWORD}"
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h postgres -U $POSTGRES_USER; do echo "Waiting for DB..."; sleep 1; done
    - |
      PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "
        CREATE TABLE IF NOT EXISTS users (
          username VARCHAR(255) PRIMARY KEY,
          firstname VARCHAR(255) NOT NULL,
          lastname VARCHAR(255) NOT NULL
        );
      "
    - npm install
    - npm test

# Here a runner will buid a Docker image : it must containt Docker CLI (=> image=docker:latest) + Docker Daemon (=> service=docker:dind)
# Note : "dind" = "Docker In Docker"
build_app:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    REGISTRY_USER: $REGISTRY_USER
    REGISTRY_PASS: $REGISTRY_PASS
    IMAGE_NAME: $IMAGE_NAME
    IMAGE_TAG: $IMAGE_TAG
  before_script:
    - cd UserApi
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS    
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .  
    - docker push $IMAGE_NAME:$IMAGE_TAG
