default:
  before_script:
    - cd UserApi/app

stages:
  - build
  - test

variables:
  POSTGRES_DB: myproject_db
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: MySecretPassword123

build_app:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build

test_app:
  stage: test
  image: node:20
  services:
    - name: postgres:15
      alias: postgres
  script:
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h postgres -U $POSTGRES_USER; do echo "Waiting for DB..."; sleep 1; done
    - |
      PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "
        CREATE TABLE users (
          id SERIAL PRIMARY KEY,
          username VARCHAR(255) NOT NULL,
          email VARCHAR(255) UNIQUE NOT NULL,
          password TEXT NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
      "
    - npm install
    - npm test
