apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
      version: v1
  template:
    metadata:
      labels:
        app: mywebapp
        version: v1
    spec:
      containers:
      - name: mywebapp
        image: ronaldlepape/dsti-devops-project:myapp-1.3.0
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      version: v2
  template:
    metadata:
      labels:
        app: mywebapp
        version: v2
    spec:
      containers:
      - name: mywebapp
        image: ronaldlepape/dsti-devops-project:myapp-1.3.0
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred        
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp
  type: ClusterIP
  ports:
    - port: 3080          # port in Kubernetes (middle layer)
      targetPort: 3000  # port in container (inner-most, matches "containerPort: 3000" above)
