# Ansible file can be played manually from inside the VM:
# vagrant@myUbuntu:/vagrant/playbooks$ ansible-playbook dev-config.yml -i localhost, -c local

---
- hosts: all
  become: true
  vars:
    db_user: myuser
    db_password: MySecretPassword123
    db_name: myproject_db

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Net Tools
      apt:
        name: net-tools
        state: present

# Install Node.JS 20.x (= latest version of this major version)
# Will be installed from Nodes's repo' instead of ubuntu apt repo (ubuntu store may be outdated)
    - name: Install Node.js 20.x
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt install -y nodejs

# Install Postgres 15 from Postgres repo
# Same comment as above
    - name: Add PostgreSQL signing key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL APT repository
      apt_repository:
        repo: 'deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main'
        state: present
        filename: 'pgdg'

    - name: Install PostgreSQL 15
      apt:
        name: postgresql-15
        state: present

# Switch local PostgreSQL authentication from peer (OS user) to md5 (password-based) 
# Why : to be accessible from a non-linux user (myuser exists only in postgres)
    - name: Find and replace "peer" with "md5" in pg_hba.conf
      replace:
        path: /etc/postgresql/15/main/pg_hba.conf
        regexp: '^local\s+all\s+all\s+peer'
        replace: 'local   all             all                                     md5'
        backup: yes

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

# Creating a Postgres user with an SQL command
    - name: Manually create PostgreSQL user (shell workaround)
      become: true
      shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}'" | grep -q 1 || \
        sudo -u postgres psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"

# Creating a Postgres database with an SQL command
    - name: Manually create PostgreSQL database (if it doesn't exist)
      become: true
      shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'" | grep -q 1 || \
        sudo -u postgres psql -c "CREATE DATABASE {{ db_name }} OWNER {{ db_user }};"

# Executing SQL commands : creating users table, adding data rows to users

    - name: Create PostgreSQL tables and insert users
      shell: |
        sudo -u postgres psql -d myproject_db -f /home/dsti_project/Postgres/01-init-users-table.sql && \
        sudo -u postgres psql -d myproject_db -f /home/dsti_project/Postgres/02-init-users.sql
      args:
        executable: /bin/bash

## Creating /home/myapp directory and copying app files from /vagrant/data
#   - name: Create /home/postgres folder and copy SQL files
#      shell: |
#        cd /home && \
#        mkdir -p myapp && \
#        cp -r /vagrant/data/app/* /home/myapp
#      args:
#        executable: /bin/bash

# Installing Docker
    - name: Instal Docker
      shell: |
        sudo apt install -y docker.io && \
        mkdir -p myapp && \
        sudo systemctl enable --now docker
      args:
        executable: /bin/bash

# Installing Docker Compose "manually" (Compose not present in apt Docker package)
    - name: Install Docker Compose
      shell: |
        sudo apt-get update && \
        sudo apt-get install -y ca-certificates curl gnupg lsb-release && \
        sudo install -m 0755 -d /etc/apt/keyrings && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
        echo \
        "deb [arch=$(dpkg --print-architecture) \
        signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
        sudo apt-get update && \
        sudo apt-get install -y docker-compose-plugin
      args:
        executable: /bin/bash

# Copying UserApi from shared folder () t o non-shared folder ("npm install" fails to create symlinks on shared folders)
# Lauching "npm install"
    - name: Copy UserApi in /home/userapi
      shell: |
        cd /home && \
        mkdir -p userapi && \
        sudo cp -r /home/dsti_project/UserApi/app/* /home/userapi  && \
        cd /home/userapi && \
        npm install
      args:
        executable: /bin/bash
