- name: Setup PostgreSQL scripts
  hosts: all
  become: true


  tasks:

# Creating a "myapp-start" script to start the app easily :-)
# The NODE_PATH tells Node where to look for node_modules directory
    - name: Create myapp-start script
      shell: |
        cat << 'EOF' | sudo tee /usr/local/bin/myapp-start > /dev/null
        #!/bin/bash
        export NODE_PATH=/home/node_tmp/node_modules
        npm run start --prefix /home/userapi &

        echo $! > /tmp/myapp.pid
        echo "myapp started in background with PID $(cat /tmp/myapp.pid)"
        EOF

        sudo chmod +x /usr/local/bin/myapp-start
      args:
        executable: /bin/bash

# Creating corresponding "myapp-stop" script to start the app easily :-)
    - name: Create myapp-stop script
      shell: |
        cat << 'EOF' | sudo tee /usr/local/bin/myapp-stop > /dev/null
        #!/bin/bash
        if [ -f /tmp/myapp.pid ]; then
          kill $(cat /tmp/myapp.pid) && echo "myapp stopped"
          rm /tmp/myapp.pid
        else
          echo "No running myapp process found."
        fi
        EOF

        sudo chmod +x /usr/local/bin/myapp-stop
      args:
        executable: /bin/bash


# Launching Docker Compose
    - name: Lauching Docker compose to start the app containers
      shell: |
        cd /home/dsti_project && \
        sudo docker compose up -d
      args:
        executable: /bin/bash

