apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyb25hbGRsZXBhcGUiLCJwYXNzd29yZCI6ImJGdDN3ajdtN0taS0VIN0MiLCJlbWFpbCI6InJvbmFsZC5sZXBhcGVAZ21haWwuY29tIiwiYXV0aCI6ImNtOXVZV3hrYkdWd1lYQmxPbUpHZEROM2FqZHROMHRhUzBWSU4wTT0ifX19
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson