apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: myuser  # Replace by true value
  POSTGRES_PASSWORD: mypassword  # Replace by true value
  POSTGRES_DB: mydatabase  # Replace by true value
