apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30900