Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.network "public_network", type: "dhcp"
  config.vm.hostname = "myUbuntu"
  
  # Sharing a folder with the host (NOTE: the host folder containing vagranfile is always shared -> /vagrant)
  config.vm.synced_folder "../", "/home/dsti_project"
  # Allows host/developper access to the running copy
  config.vm.synced_folder "../UserApi_running", "/home/userapi"

  # Copying file from host to VM
  #config.vm.provision "file", source: "copiedfile.txt", destination: "/home/vagrant/copiedfile.txt"

  # Giving a friendly name in VirtualBox GUI and managing CPU/RAM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ronald's-development-machine"
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end

  # Update package cache before installing anything
  config.vm.provision "shell", inline: <<-SHELL
    echo "Running apt-get update..."
    apt-get update
    apt-get install -y ansible
  SHELL

  # Provisions Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.install = false
    ansible.playbook = "/vagrant/playbooks/dev-config.yml"
    ansible.extra_vars = {ansible_remote_tmp: "/tmp"}
  end

end